version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
  pre_build:
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Building Lambda deployment package..."
      - zip -r raju.zip . -x "*.yml*"
      - aws lambda update-function-code --function-name raju_lambda --zip-file fileb://raju.zip
      - sleep 10
      # - aws lambda invoke --function-name my-function --payload file://./event.json output.json
      # - cat output.json
  post_build:
    commands:
      - echo "Lambda deployment package created successfully."
